import Link from "next/link";
import { localizedPath, localeHomeLabels, type Locale } from "../lib/site-data";
import { SiteFrame } from "./site-frame";

type LegalKind = "privacy" | "terms";
type LegalContent = { title: string; lede: string; sections: Array<{ heading: string; body: string }> };

const legalCopy: Record<Locale, Record<LegalKind, LegalContent>> = {
  en: {
    privacy: { title: "Privacy Policy", lede: "This independent fan wiki is designed as a source-labeled reference site.", sections: [{ heading: "Information handled by this site", body: "The current site does not provide account registration, comment forms, or a custom contact form. It does not ask you to submit personal information to read the pages." }, { heading: "External services", body: "Links to the official Mistfall Hunter website, Steam, Discord, YouTube, X, and other destinations are external sites. Their own privacy policies apply when you leave this wiki." }, { heading: "Changes", body: "This page may be updated if the site adds a feature that changes how information is handled. Game details are kept separate from this policy and tied to the source context used by the wiki." }] },
    terms: { title: "Terms of Service", lede: "By using this independent fan wiki, you agree to use it as a reference and verify important game information with official sources.", sections: [{ heading: "Independent fan site", body: "Mistfall Hunter Wiki is not affiliated with Bellring Games or Skystone Games. Mistfall Hunter names, logos, and official materials belong to their respective owners." }, { heading: "Accuracy and updates", body: "The site uses official links and a dated research snapshot. Game systems can change. Source-labeled pages can become outdated after an update, so verify important details with the linked official channels." }, { heading: "External links", body: "External links are provided for verification and convenience. Their availability and terms are controlled by the linked service." }] },
  },
  ru: {
    privacy: { title: "Политика конфиденциальности", lede: "Независимая фанатская вики работает как справочный сайт с указанием источников.", sections: [{ heading: "Какие данные обрабатываются", body: "На текущем сайте нет регистрации, комментариев и формы связи. Для чтения страниц не нужно отправлять личные данные." }, { heading: "Внешние сервисы", body: "Ссылки на официальный сайт Mistfall Hunter, Steam, Discord, YouTube и X ведут на внешние сервисы, где действуют их собственные политики." }, { heading: "Изменения", body: "Политика будет обновлена, если сайт добавит функцию, меняющую обработку данных." }] },
    terms: { title: "Условия использования", lede: "Используя независимую фанатскую вики, сверяйте важную информацию с официальными источниками.", sections: [{ heading: "Независимый сайт", body: "Mistfall Hunter Wiki не связана с Bellring Games или Skystone Games. Названия, логотипы и материалы принадлежат соответствующим владельцам." }, { heading: "Точность и обновления", body: "Сайт использует официальные ссылки и датированный исследовательский снимок. Игровые системы меняются, поэтому важные детали следует сверять с официальными каналами после обновлений." }, { heading: "Внешние ссылки", body: "Внешние ссылки даны для проверки; их доступность и условия определяет соответствующий сервис." }] },
  },
  de: {
    privacy: { title: "Datenschutzerklärung", lede: "Dieses unabhängige Fan-Wiki ist eine quellenmarkierte Referenzseite.", sections: [{ heading: "Verarbeitete Informationen", body: "Die aktuelle Seite bietet keine Registrierung, Kommentare oder Kontaktformulare. Zum Lesen müssen keine personenbezogenen Daten übermittelt werden." }, { heading: "Externe Dienste", body: "Links zu offizieller Website, Steam, Discord, YouTube und X führen zu externen Diensten mit eigenen Datenschutzregeln." }, { heading: "Änderungen", body: "Diese Seite wird aktualisiert, wenn eine neue Funktion die Datenverarbeitung verändert." }] },
    terms: { title: "Nutzungsbedingungen", lede: "Nutze dieses unabhängige Fan-Wiki als Referenz und prüfe wichtige Informationen bei offiziellen Quellen.", sections: [{ heading: "Unabhängige Seite", body: "Mistfall Hunter Wiki ist nicht mit Bellring Games oder Skystone Games verbunden. Namen, Logos und offizielle Materialien gehören ihren jeweiligen Eigentümern." }, { heading: "Richtigkeit und Updates", body: "Die Seite nutzt offizielle Links und einen datierten Recherche-Snapshot. Spielsysteme ändern sich; wichtige Details sollten nach Updates über die offiziellen Kanäle geprüft werden." }, { heading: "Externe Links", body: "Externe Links dienen der Prüfung; Verfügbarkeit und Bedingungen bestimmt der jeweilige Dienst." }] },
  },
  "pt-br": {
    privacy: { title: "Política de privacidade", lede: "Esta wiki independente feita por fãs funciona como um site de referência com fontes.", sections: [{ heading: "Informações tratadas", body: "O site atual não oferece cadastro, comentários ou formulário de contato. Você não precisa enviar dados pessoais para ler as páginas." }, { heading: "Serviços externos", body: "Links para o site oficial de Mistfall Hunter, Steam, Discord, YouTube e X levam a serviços externos com suas próprias políticas." }, { heading: "Alterações", body: "Esta página será atualizada se uma nova funcionalidade mudar o tratamento de informações." }] },
    terms: { title: "Termos de uso", lede: "Use esta wiki independente como referência e confirme informações importantes em fontes oficiais.", sections: [{ heading: "Site independente", body: "Mistfall Hunter Wiki não é afiliada à Bellring Games ou à Skystone Games. Nomes, logos e materiais oficiais pertencem a seus respectivos proprietários." }, { heading: "Precisão e atualizações", body: "O site usa links oficiais e um snapshot de pesquisa datado. Os sistemas do jogo mudam; confira detalhes importantes nos canais oficiais depois das atualizações." }, { heading: "Links externos", body: "Links externos são fornecidos para conferência; sua disponibilidade e termos são controlados pelo serviço vinculado." }] },
  },
  zh: {
    privacy: { title: "隐私政策", lede: "本独立玩家 Wiki 是一个标注来源的参考站。", sections: [{ heading: "本网站处理的信息", body: "当前网站没有账号注册、评论表单或自定义联系表单。阅读页面不需要向本站提交个人信息。" }, { heading: "外部服务", body: "官网、Steam、Discord、YouTube、X 等链接会跳转到外部网站；离开本 Wiki 后适用对方自己的隐私政策。" }, { heading: "政策变更", body: "如果网站新增功能并改变信息处理方式，本页会同步更新。" }] },
    terms: { title: "服务条款", lede: "使用本独立玩家 Wiki，即表示你将其作为参考，并会对重要信息回到官方来源核验。", sections: [{ heading: "独立玩家站", body: "Mistfall Hunter Wiki 与 Bellring Games 或 Skystone Games 没有隶属关系。游戏名称、Logo 与官方素材归各自权利人所有。" }, { heading: "准确性与更新", body: "网站使用官方链接与带日期的调研快照。游戏系统可能更新，重要信息请在版本变化后回到官方渠道核验，本站不保证内容长期不变。" }, { heading: "外部链接", body: "外部链接用于核验和访问，链接服务的可用性与条款由对方控制。" }] },
  },
};

export function LegalPage({ locale, kind }: { locale: Locale; kind: LegalKind }) {
  const copy = legalCopy[locale][kind];
  return <SiteFrame locale={locale} currentPath={`/${kind === "privacy" ? "privacy-policy" : "terms-of-service"}`}><article className="reference-article legal-article"><nav className="breadcrumbs"><Link href={localizedPath(locale, "/")}>{localeHomeLabels[locale]}</Link><span>›</span><span>{copy.title}</span></nav><h1>{copy.title}</h1><p className="article-lede">{copy.lede}</p><div className="article-copy">{copy.sections.map((section) => <section className="legal-section" key={section.heading}><h2>{section.heading}</h2><p>{section.body}</p></section>)}</div></article></SiteFrame>;
}
