import Link from "next/link";
import { getKeywordArticle } from "../lib/keyword-pages";
import { classRecords, localizedPath, type Locale } from "../lib/site-data";
import { ResearchArticles } from "./research-content";
import { SiteFrame } from "./site-frame";

const copy: Record<Locale, { breadcrumb: string; title: string; lede: string; intro: string; warning: string; warningCopy: string; guides: string; media: string; read: string }> = {
  en: { breadcrumb: "Classes", title: "Classes Overview", lede: "Xbox Wire confirms six playable classes and the collected class-selection material names Blackarrow, Mercenary, Seer, Shadowstrix, Sorcerer, and Withered Knight. Exact balance values remain 待确认.", intro: "The official description confirms six classes, two weapon stances per class, talent trees, gem affixes, active skills, solo play, and three-player squads. The class names and role notes below come from the collected guide material; exact skill numbers and balance are still 待确认.", warning: "⚠️ Official scope and reported class detail", warningCopy: "Use the official platform descriptions for the feature scope, then treat individual weapon paths and class recommendations as source-labeled guide information. The research body below keeps those two evidence levels separate.", guides: "Class Reference Pages", media: "Official media", read: "Read more" },
  ru: { breadcrumb: "Классы", title: "Обзор классов", lede: "Официальная страница Steam указывает шесть игровых классов. Названия и детали каждого класса в текущем снимке ожидают подтверждения.", intro: "Исследовательский бриф подтверждает шесть классов, стойки оружия, деревья талантов, аффиксы самоцветов и активные навыки. Названия классов, списки навыков и баланс пока не подтверждены.", warning: "⚠️ Детали классов — ожидают проверки", warningCopy: "Проверяйте официальную страницу Steam и официальные каналы игры. Мы добавим конкретные маршруты только после проверки источника.", guides: "Страницы классов", media: "Официальный материал", read: "Подробнее" },
  de: { breadcrumb: "Klassen", title: "Klassenübersicht", lede: "Die offizielle Steam-Seite nennt sechs spielbare Klassen. Namen und Details sind im aktuellen Recherche-Snapshot zu bestätigen.", intro: "Der Recherchebrief bestätigt sechs Klassen, Waffenhaltungen, Talentbäume, Edelstein-Affixe und aktive Skills. Einzelne Namen, Skill-Listen und Balancewerte sind hier noch nicht bestätigt.", warning: "⚠️ Klassendetails — zu bestätigen", warningCopy: "Nutze die offizielle Steam-Seite und offiziellen Kanäle als Quelle. Konkrete Routen werden erst nach verifizierten Informationen ergänzt.", guides: "Klassen-Referenzen", media: "Offizielles Material", read: "Mehr lesen" },
  "pt-br": { breadcrumb: "Classes", title: "Visão geral das classes", lede: "A página oficial da Steam lista seis classes jogáveis. Os nomes e detalhes individuais estão a confirmar neste snapshot.", intro: "O material da pesquisa confirma seis classes, posturas de arma, árvores de talentos, afixos de gemas e habilidades ativas. Nomes, listas de habilidades e balanceamento ainda não foram confirmados.", warning: "⚠️ Detalhes das classes — a confirmar", warningCopy: "Use a página oficial da Steam e os canais oficiais como referência. Rotas específicas serão adicionadas depois da verificação.", guides: "Páginas de referência das classes", media: "Mídia oficial", read: "Ler mais" },
  zh: { breadcrumb: "职业", title: "职业总览", lede: "Xbox Wire 确认有 6 个可玩职业，现有职业调研资料列出 Blackarrow、Mercenary、Seer、Shadowstrix、Sorcerer 与 Withered Knight；具体平衡数值仍待确认。", intro: "官方描述确认 6 个职业、每个职业的两种武器姿态、天赋树、宝石词缀、主动技能、单人玩法和三人小队。下面的职业名称与定位来自已收集攻略，会标注与官方功能描述不同的证据层级。", warning: "⚠️ 官方范围与攻略资料", warningCopy: "功能范围以官方平台描述为准，具体武器路线与职业推荐只作为标注来源的攻略信息。下方正文会保留待确认边界。", guides: "职业参考页", media: "官方素材", read: "阅读更多" },
};

export function ClassesPage({ locale }: { locale: Locale }) {
  const text = copy[locale];
  const records = classRecords[locale];
  const classArticle = getKeywordArticle("mistfall-hunter-classes");
  const researchContent = classArticle && (locale === "en" || locale === "zh") ? <ResearchArticles articles={[classArticle]} locale={locale} /> : null;
  return <SiteFrame locale={locale} currentPath="/classes"><article className="reference-article"><nav className="breadcrumbs"><Link href={localizedPath(locale, "/")}>{locale === "zh" ? "首页" : "Home"}</Link><span>›</span><span>{text.breadcrumb}</span></nav><div className="article-media"><img src="/images/mistfall/heroes.jpg" alt="Mistfall Hunter official class artwork" /><span>{text.media}</span></div><h1>{text.title}</h1><p className="article-lede">{text.lede}</p><div className="ad-slot" aria-hidden="true" /><div className="article-copy"><p>{text.intro}</p><p className="warning-copy">{text.warning}</p><p>{text.warningCopy}</p><h2>{text.guides}</h2><div className="guide-grid">{records.map((record) => <Link className="guide-card" href={localizedPath(locale, `/classes/${record.slug}`)} key={record.slug}><div className="guide-card-copy">{record.tag ? <span className="badge">{record.tag}</span> : null}<h3>{record.title}</h3><p>{record.description}</p><span className="read-more">{text.read} <b>→</b></span></div></Link>)}</div></div>{researchContent}</article></SiteFrame>;
}

export const RacesPage = ClassesPage;
