import Link from "next/link";
import { getKeywordArticle } from "../lib/keyword-pages";
import { classRecords, localizedPath, localeHomeLabels, type Locale } from "../lib/site-data";
import { ResearchArticles } from "./research-content";
import { SiteFrame } from "./site-frame";

const copy: Record<Locale, { breadcrumb: string; title: string; lede: string; intro: string; warning: string; warningCopy: string; guides: string; media: string; read: string }> = {
  en: { breadcrumb: "Classes", title: "Classes Overview", lede: "Xbox Wire confirms six playable classes, and the collected class-selection material names Blackarrow, Mercenary, Seer, Shadowstrix, Sorcerer, and Withered Knight.", intro: "The official description confirms six classes, two weapon stances per class, talent trees, gem affixes, active skills, solo play, and three-player squads. The class names and role notes below come from the collected guide material; numeric skill tables are not included in this overview.", warning: "⚠️ Official scope and reported class detail", warningCopy: "Use the official platform descriptions for the feature scope, then treat individual weapon paths and class recommendations as source-labeled guide information. The research body below keeps those two evidence levels separate.", guides: "Class Reference Pages", media: "Official media", read: "Read more" },
  ru: { breadcrumb: "Классы", title: "Обзор классов", lede: "Официальная страница Steam указывает шесть игровых классов; собранный материал называет Blackarrow, Mercenary, Seer, Shadowstrix, Sorcerer и Withered Knight.", intro: "Исследовательский бриф подтверждает шесть классов, стойки оружия, деревья талантов, аффиксы самоцветов и активные навыки. Ниже названия и ролевые заметки привязаны к собранным гайдам, а числовые таблицы навыков в этот обзор не включены.", warning: "⚠️ Официальный охват и детали из гайдов", warningCopy: "Используйте официальную страницу Steam и официальные каналы для общего набора функций, а отдельные пути оружия и рекомендации классов читайте как материалы с указанным источником.", guides: "Страницы классов", media: "Официальный материал", read: "Подробнее" },
  de: { breadcrumb: "Klassen", title: "Klassenübersicht", lede: "Die offizielle Steam-Seite nennt sechs spielbare Klassen; das gesammelte Material nennt Blackarrow, Mercenary, Seer, Shadowstrix, Sorcerer und Withered Knight.", intro: "Der Recherchebrief bestätigt sechs Klassen, Waffenhaltungen, Talentbäume, Edelstein-Affixe und aktive Skills. Namen und Rollen unten stammen aus dem gesammelten Material; numerische Skill-Tabellen sind in dieser Übersicht nicht enthalten.", warning: "⚠️ Offizieller Umfang und Guide-Details", warningCopy: "Nutze die offizielle Steam-Seite und offizielle Kanäle für den Funktionsumfang. Einzelne Waffenpfade und Klassenempfehlungen sind als quellenmarkierte Guide-Informationen zu lesen.", guides: "Klassen-Referenzen", media: "Offizielles Material", read: "Mehr lesen" },
  "pt-br": { breadcrumb: "Classes", title: "Visão geral das classes", lede: "A página oficial da Steam lista seis classes jogáveis; o material coletado nomeia Blackarrow, Mercenary, Seer, Shadowstrix, Sorcerer e Withered Knight.", intro: "O material da pesquisa confirma seis classes, posturas de arma, árvores de talentos, afixos de gemas e habilidades ativas. Os nomes e funções abaixo vêm dos guias coletados; esta visão geral não inclui tabelas numéricas de habilidades.", warning: "⚠️ Escopo oficial e detalhes dos guias", warningCopy: "Use a página oficial da Steam e os canais oficiais para o escopo de recursos. Caminhos de armas e recomendações de classe devem ser lidos como informações de guias com fonte indicada.", guides: "Páginas de referência das classes", media: "Mídia oficial", read: "Ler mais" },
  zh: { breadcrumb: "职业", title: "职业总览", lede: "Xbox Wire 确认有 6 个可玩职业，现有职业调研资料列出 Blackarrow、Mercenary、Seer、Shadowstrix、Sorcerer 与 Withered Knight。", intro: "官方描述确认 6 个职业、每个职业的两种武器姿态、天赋树、宝石词缀、主动技能、单人玩法和三人小队。下面的职业名称与定位来自已收集攻略；本总览不放入逐职业数值表。", warning: "⚠️ 官方范围与攻略资料", warningCopy: "功能范围以官方平台描述为准，具体武器路线与职业推荐只作为标注来源的攻略信息。", guides: "职业参考页", media: "官方素材", read: "阅读更多" },
};

export function ClassesPage({ locale }: { locale: Locale }) {
  const text = copy[locale];
  const records = classRecords[locale];
  const classArticle = getKeywordArticle("mistfall-hunter-classes");
  const researchContent = classArticle && locale === "en" ? <ResearchArticles articles={[classArticle]} locale={locale} /> : null;
  return <SiteFrame locale={locale} currentPath="/classes"><article className="reference-article"><nav className="breadcrumbs"><Link href={localizedPath(locale, "/")}>{localeHomeLabels[locale]}</Link><span>›</span><span>{text.breadcrumb}</span></nav><div className="article-media"><img src="/images/mistfall/heroes.jpg" alt="Mistfall Hunter official class artwork" /><span>{text.media}</span></div><h1>{text.title}</h1><p className="article-lede">{text.lede}</p><div className="ad-slot" aria-hidden="true" /><div className="article-copy"><p>{text.intro}</p><p className="warning-copy">{text.warning}</p><p>{text.warningCopy}</p><h2>{text.guides}</h2><div className="guide-grid">{records.map((record) => <Link className="guide-card" href={localizedPath(locale, `/classes/${record.slug}`)} key={record.slug}><div className="guide-card-copy">{record.tag ? <span className="badge">{record.tag}</span> : null}<h3>{record.title}</h3><p>{record.description}</p><span className="read-more">{text.read} <b>→</b></span></div></Link>)}</div></div>{researchContent}</article></SiteFrame>;
}

export const RacesPage = ClassesPage;
