import Link from "next/link";
import { localizedPath, localeHomeLabels, officialLinks, type Locale, siteCopy } from "../lib/site-data";
import { getReferenceResearchArticles, type ReferenceResearchKey, ResearchArticles } from "./research-content";
import { SiteFrame } from "./site-frame";

export type SectionKey = "beginner-guide" | "extraction" | "bosses" | "tier-list" | "updates" | "community" | "maps-and-loot";

type SectionContent = { title: string; lede: string; paragraphs: string[]; bullets: string[] };

const sectionCopy: Record<Locale, Record<SectionKey, SectionContent>> = {
  en: {
    "beginner-guide": { title: "Beginner Guide", lede: "Start with the controls, first loadout, extraction loop, and safe early routes described in the research brief.", paragraphs: ["Mistfall Hunter is a high-stakes PvPvE extraction ARPG. Learn the basic controls and extraction loop before risking valuable gear."], bullets: ["Understand the extraction loop before risking valuable gear.", "Use the official channels for current control and system changes."] },
    extraction: { title: "How Extraction Works", lede: "The research brief describes solo and trio runs, map objectives, Returner Woodlings, and the need to leave with your haul.", paragraphs: ["A successful run means making progress and extracting your loot before the mist takes everything."], bullets: ["Solo and three-player squad play are listed in the research brief.", "Returner Woodlings are named as an extraction element."] },
    bosses: { title: "Bosses & Mist Lords", lede: "Official Xbox material places Corroded creatures and Mist Lords in the ruins and names the Returner Woodling as the extraction element.", paragraphs: ["The official description frames Mist Lords as PvE threats alongside Corroded creatures and rival Gyldhunters. It also names the Returner Woodling as the way to extract, which gives encounters a clear risk-and-reward context without proving a boss strategy.", "The collected official material does not provide a complete boss table, phase list, drop table, or numeric difficulty table, so this page stays with the threats and extraction elements named by the source."], bullets: ["Corroded creatures and Mist Lords: named in the official Xbox description.", "Returner Woodling: named as the extraction element."] },
    "tier-list": { title: "Tier List", lede: "A verified class ranking is not available in the current research materials.", paragraphs: ["The collected class sources describe roles, skills, and build directions but do not establish a universal ranking. This wiki therefore keeps the page as a source-labeled comparison rather than fabricating a tier list."], bullets: ["Playable classes listed: 6.", "Use the class reference pages to compare reported roles and build directions."] },
    updates: { title: "Official Updates", lede: "A source-labeled timeline for the official live updates and roadmap status.", paragraphs: ["The official Steam notices report an August 12, 2026 update with Soul Harvest, a Fate Chart stage, a World Chat blocklist function, Xbox real-time voice chat, balance changes, and bug fixes. An August 14 notice says server configuration adjustments reduced intermittent stuttering, while optimization remains ongoing."], bullets: ["Aug 12, 2026 — Soul Harvest and other live-update changes.", "Aug 14, 2026 — server-stutter optimization status; issues are still being investigated.", "Brandrgarde Solo — official roadmap target for the middle of Season 1, September."] },
    community: { title: "Official Community & Links", lede: "Use the official website, Steam pages, Discord directory, X account, and YouTube channel for primary updates.", paragraphs: ["This wiki links to official destinations only. Community tools, mirrors, and third-party guides are not treated as primary sources."], bullets: [] },
    "maps-and-loot": { title: "Maps, Bosses & Loot", lede: "The research brief names Gyldenmist, Mist Lords, relics, loot priorities, and harder expeditions as core reference topics.", paragraphs: ["The current brief names these map and loot topics but does not include full tables. This page therefore stays with the source-named setting pressure, rewards, and expedition themes."], bullets: ["Gyldenmist: named as the setting pressure.", "Relics and loot: named as extraction rewards."] },
  },
  ru: {
    "beginner-guide": { title: "Гайд новичка", lede: "Начните с управления, первого комплекта, цикла extraction и безопасных маршрутов.", paragraphs: ["Mistfall Hunter — PvPvE extraction ARPG с высокой ценой ошибки. Изучите базовое управление и цикл extraction перед риском ценной экипировки."], bullets: ["Изучите цикл extraction перед риском ценной экипировки.", "Следите за официальными каналами за изменениями управления и систем."] },
    extraction: { title: "Как работает extraction", lede: "В брифе указаны одиночные и троечные рейды, цели карты и Returner Woodling.", paragraphs: ["Нужно вынести добычу до того, как туман заберёт всё."], bullets: ["Одиночная игра и отряд из трёх игроков.", "Returner Woodling назван элементом эвакуации."] },
    bosses: { title: "Боссы и Mist Lords", lede: "Официальный материал Xbox помещает Corroded и Mist Lords в руины и называет Returner Woodling элементом эвакуации.", paragraphs: ["В официальном описании Mist Lords названы PvE-угрозой наряду с Corroded и соперниками-Gyldhunter. Returner Woodling назван способом эвакуации, что задаёт контекст риска и награды без выдуманной тактики босса.", "Собранный официальный материал не содержит полной таблицы боссов, фаз, дропа или числовой сложности, поэтому страница ограничена названными источником угрозами и элементами эвакуации."], bullets: ["Corroded и Mist Lords: названы в официальном описании Xbox.", "Returner Woodling: назван элементом эвакуации."] },
    "tier-list": { title: "Тир-лист", lede: "Проверенного рейтинга классов в текущих материалах нет.", paragraphs: ["Собранные источники описывают роли, навыки и направления билдов, но не устанавливают универсальный рейтинг. Поэтому страница остаётся сравнением с указанием источников, без выдуманного тир-листа."], bullets: ["Игровых классов: 6.", "Для сравнения используйте страницы классов и описанные в источниках направления билдов."] },
    updates: { title: "Официальные обновления", lede: "Таймлайн официальных объявлений и исследовательских снимков.", paragraphs: ["Официальное сообщение Steam от 15 августа сообщает, что изменения конфигурации серверов снизили частоту фризов, но оптимизация продолжается. В сообщении Fair Play от 12 августа игроков просят жаловаться на читы и незаконный тиминг; функция письма о результате жалобы запланирована. Награды Soul Harvest отправляются внутриигровой почтой, а не кодом."], bullets: ["15 авг. 2026 — серверные настройки снизили фризы; оптимизация продолжается; награды Soul Harvest через внутриигровую почту.", "12 авг. 2026 — сообщение Fair Play о читах и незаконном тиминге.", "13 авг. 2026 — 14 941 онлайн в исследовательском снимке."] },
    community: { title: "Официальное сообщество", lede: "Официальный сайт, страницы Steam, Discord, X и YouTube — основные источники.", paragraphs: ["Здесь собраны только официальные направления. Непроверенные руководства не считаются первичным источником."], bullets: [] },
    "maps-and-loot": { title: "Карты, боссы и добыча", lede: "В брифе названы Gyldenmist, Mist Lords, реликвии, добыча и сложные экспедиции.", paragraphs: ["В текущем брифе названы эти темы карт и добычи, но нет полных таблиц. Поэтому страница ограничена названными источником элементами мира, наградами и экспедициями."], bullets: ["Gyldenmist назван источником давления мира.", "Реликвии и добыча названы наградами extraction."] },
  },
  de: {
    "beginner-guide": { title: "Einsteiger-Guide", lede: "Beginne mit Steuerung, erstem Loadout, Extraction-Loop und sicheren frühen Routen.", paragraphs: ["Mistfall Hunter ist ein PvPvE-Extraction-ARPG mit hohem Risiko. Lerne die grundlegende Steuerung und den Extraction-Loop vor wertvoller Ausrüstung."], bullets: ["Lerne den Extraction-Loop vor wertvoller Ausrüstung.", "Nutze offizielle Kanäle für Änderungen an Steuerung und Systemen."] },
    extraction: { title: "Wie Extraction funktioniert", lede: "Der Recherchebrief nennt Solo- und Dreierläufe, Kartenziele und Returner Woodling.", paragraphs: ["Die Beute muss vor dem Nebel extrahiert werden."], bullets: ["Solo und Dreierteam sind gelistet.", "Returner Woodling wird als Extraction-Element genannt."] },
    bosses: { title: "Bosse und Mist Lords", lede: "Offizielles Xbox-Material platziert Corroded und Mist Lords in den Ruinen und nennt Returner Woodling als Extraction-Element.", paragraphs: ["Die offizielle Beschreibung nennt Mist Lords als PvE-Bedrohung neben Corroded und rivalisierenden Gyldhuntern. Returner Woodling wird als Weg zur Extraction genannt und liefert den Risiko-und-Belohnungs-Kontext ohne eine erfundene Boss-Taktik.", "Das gesammelte offizielle Material enthält keine vollständige Boss-, Phasen-, Drop- oder Schwierigkeits-Tabelle. Daher bleibt die Seite bei den vom Material genannten Bedrohungen und Extraction-Elementen."], bullets: ["Corroded und Mist Lords: im offiziellen Xbox-Material genannt.", "Returner Woodling: als Extraction-Element genannt."] },
    "tier-list": { title: "Tier-Liste", lede: "Eine verifizierte Klassenrangliste liegt in den aktuellen Materialien nicht vor.", paragraphs: ["Die gesammelten Quellen beschreiben Rollen, Skills und Build-Richtungen, legen aber kein universelles Ranking fest. Diese Seite bleibt deshalb ein quellenmarkierter Vergleich ohne erfundene Tier-Liste."], bullets: ["Spielbare Klassen: 6.", "Nutze die Klassenseiten zum Vergleich der berichteten Rollen und Build-Richtungen."] },
    updates: { title: "Offizielle Updates", lede: "Eine quellenmarkierte Timeline zu offiziellen Mitteilungen und Recherche-Snapshots.", paragraphs: ["Die offizielle Steam-Mitteilung vom 15. August sagt, dass Serveranpassungen die Häufigkeit von Stottern verringerten, die Optimierung aber weiterläuft. Die Fair-Play-Mitteilung vom 12. August bittet um Meldungen zu Cheats und illegalem Teaming; eine E-Mail zum Ergebnis der Meldung ist geplant. Soul-Harvest-Belohnungen kommen per In-Game-Post, nicht als Code."], bullets: ["15. Aug. 2026 — Serveranpassungen verringerten Stottern; Optimierung läuft weiter; Soul-Harvest-Belohnungen per In-Game-Post.", "12. Aug. 2026 — Fair-Play-Mitteilung zu Cheats und illegalem Teaming.", "13. Aug. 2026 — 14.941 online im Recherche-Snapshot."] },
    community: { title: "Offizielle Community", lede: "Offizielle Website, Steam, Discord, X und YouTube sind die primären Quellen.", paragraphs: ["Diese Seite verlinkt nur offizielle Ziele. Unverifizierte Guides gelten nicht als Primärquelle."], bullets: [] },
    "maps-and-loot": { title: "Karten, Bosse und Beute", lede: "Der Brief nennt Gyldenmist, Mist Lords, Relikte, Beuteprioritäten und Expeditionen.", paragraphs: ["Der aktuelle Brief nennt diese Karten- und Beute-Themen, enthält aber keine vollständigen Tabellen. Die Seite bleibt daher bei den im Material genannten Welt-, Belohnungs- und Expeditionselementen."], bullets: ["Gyldenmist wird als Weltdruck genannt.", "Relikte und Beute werden als Extraction-Ziele genannt."] },
  },
  "pt-br": {
    "beginner-guide": { title: "Guia para iniciantes", lede: "Comece pelos controles, primeiro equipamento, ciclo de extração e rotas seguras.", paragraphs: ["Mistfall Hunter é um extraction ARPG PvPvE de alto risco. Aprenda os controles básicos e o ciclo de extração antes de arriscar equipamentos valiosos."], bullets: ["Aprenda o ciclo de extração antes de arriscar equipamentos valiosos.", "Acompanhe os canais oficiais para mudanças de controles e sistemas."] },
    extraction: { title: "Como funciona a extração", lede: "O material cita incursões solo ou em trio, objetivos do mapa e Returner Woodling.", paragraphs: ["Extraia o saque antes que a névoa leve tudo."], bullets: ["Jogo solo e grupo de três jogadores.", "Returner Woodling é citado como elemento de extração."] },
    bosses: { title: "Chefes e Mist Lords", lede: "O material oficial do Xbox coloca Corroded e Mist Lords nas ruínas e cita Returner Woodling como elemento de extração.", paragraphs: ["A descrição oficial apresenta Mist Lords como ameaças PvE ao lado de Corroded e Gyldhunters rivais. Returner Woodling é citado como forma de extração, criando o contexto de risco e recompensa sem justificar uma tática inventada de chefe.", "O material oficial coletado não traz uma tabela completa de chefes, fases, drops ou dificuldade numérica. Por isso, a página fica nos elementos de ameaça e extração nomeados pelas fontes."], bullets: ["Corroded e Mist Lords: citados no material oficial do Xbox.", "Returner Woodling: citado como elemento de extração."] },
    "tier-list": { title: "Tier List", lede: "Não há ranking de classes verificado nos materiais atuais.", paragraphs: ["As fontes coletadas descrevem funções, habilidades e direções de build, mas não estabelecem um ranking universal. Esta página permanece uma comparação com fontes identificadas, sem inventar uma tier list."], bullets: ["Classes jogáveis: 6.", "Use as páginas de classe para comparar funções e direções de build relatadas."] },
    updates: { title: "Atualizações oficiais", lede: "Linha do tempo com os avisos oficiais e os snapshots da pesquisa.", paragraphs: ["O aviso oficial da Steam de 15 de agosto diz que ajustes nos servidores reduziram a frequência dos travamentos, mas a otimização continua. O aviso de Fair Play de 12 de agosto pede denúncias de trapaça e teaming ilegal; um e-mail sobre o resultado da denúncia está planejado. As recompensas de Soul Harvest chegam pelo correio do jogo, não por código."], bullets: ["15 ago. 2026 — ajustes nos servidores reduziram travamentos; otimização continua; recompensas de Soul Harvest por correio do jogo.", "12 ago. 2026 — aviso de Fair Play sobre trapaças e teaming ilegal.", "13 ago. 2026 — 14.941 online no snapshot da pesquisa."] },
    community: { title: "Comunidade oficial", lede: "Site oficial, páginas da Steam, Discord, X e YouTube são as fontes primárias.", paragraphs: ["Esta página usa apenas destinos oficiais. Guias não verificados não são tratados como fontes primárias."], bullets: [] },
    "maps-and-loot": { title: "Mapas, chefes e saque", lede: "O material cita Gyldenmist, Mist Lords, relíquias, saque e expedições difíceis.", paragraphs: ["O briefing atual nomeia esses temas de mapas e saque, mas não inclui tabelas completas. A página permanece nos elementos de mundo, recompensas e expedições citados pelas fontes."], bullets: ["Gyldenmist é citado como pressão do mundo.", "Relíquias e saque são citados como objetivos."] },
  },
  zh: {
    "beginner-guide": { title: "新手指南", lede: "从操作、第一套装备、撤离循环与安全的前期路线开始。", paragraphs: ["Mistfall Hunter 是一款高风险 PvPvE 撤离 ARPG。承担高价值装备风险前，先了解基础操作和撤离循环。"], bullets: ["承担高价值装备风险前先了解撤离循环。", "版本变化以官方频道为准。"] },
    extraction: { title: "撤离如何运作", lede: "调研资料提到单人和三人小队、地图目标、Returner Woodling，以及带着战利品离开。", paragraphs: ["需要在迷雾夺走一切前完成撤离。"], bullets: ["资料列出单人和三人小队。", "Returner Woodling 被列为撤离要素。"] },
    bosses: { title: "首领与 Mist Lords", lede: "Xbox 官方资料将 Corroded 生物与 Mist Lords 放在遗迹场景中，并提到 Returner Woodling 是撤离要素。", paragraphs: ["官方描述把 Mist Lords 与 Corroded 生物、敌对 Gyldhunters 一起列为 PvE 威胁，并提到通过 Returner Woodling 完成撤离。这说明战斗与带出战利品之间存在风险收益关系，但不能据此编造首领攻略。", "当前收集的官方资料没有完整首领表、阶段列表、掉落表或数值难度表，因此本页只保留来源明确提到的威胁与撤离要素。"], bullets: ["Corroded 生物与 Mist Lords：Xbox 官方描述提到。", "Returner Woodling：官方描述中的撤离要素。"] },
    "tier-list": { title: "强度榜", lede: "当前调研资料没有可核验的职业排名。", paragraphs: ["收集到的职业资料描述了定位、技能与配装方向，但没有建立统一排名。因此本页作为标注来源的对比入口，不编造强度榜。"], bullets: ["资料列出的可玩职业：6 个。", "可通过职业页比较来源中出现的定位与配装方向。"] },
    updates: { title: "官方更新", lede: "标注来源的官方实时更新与路线图状态。", paragraphs: ["Steam 官方公告记录了 2026 年 8 月 12 日更新：加入 Soul Harvest、命运图表新阶段、世界聊天屏蔽功能、Xbox 实时语音聊天，以及职业平衡和问题修复。8 月 14 日公告称已调整所有服务器配置以减少间歇性卡顿，但优化仍在继续。"], bullets: ["2026/08/12——Soul Harvest 与其他实时更新内容。", "2026/08/14——服务器卡顿优化状态；问题仍在排查。", "Brandrgarde Solo——官方路线图目标为 S1 中期、9 月。"] },
    community: { title: "官方社区与链接", lede: "通过官网、Steam 页面、Discord 目录、X 与 YouTube 获取一手更新。", paragraphs: ["本 Wiki 只链接官方目的地。第三方镜像和未核验攻略不作为一手来源。"], bullets: [] },
    "maps-and-loot": { title: "地图、首领与战利品", lede: "调研资料将 Gyldenmist、Mist Lords、遗物、战利品优先级与高难远征列为核心参考主题。", paragraphs: ["当前资料列出了这些地图与战利品主题，但没有完整表格。因此本页只保留来源明确提到的世界、奖励与远征要素。"], bullets: ["Gyldenmist 被列为世界压力来源。", "遗物与战利品被列为撤离目标。"] },
  },
};

export function ReferenceSectionPage({ locale, section }: { locale: Locale; section: SectionKey }) {
  const copy = sectionCopy[locale][section];
  const site = siteCopy[locale];
  const isCommunity = section === "community";
  const researchKey = section as ReferenceResearchKey;
  const researchArticles = section === "bosses" || section === "community" ? [] : getReferenceResearchArticles(researchKey);
  const useResearch = locale === "en" && researchArticles.length > 0;
  return <SiteFrame locale={locale} currentPath={`/${section}`}><article className="reference-article"><nav className="breadcrumbs"><Link href={localizedPath(locale, "/")}>{localeHomeLabels[locale]}</Link><span>›</span><span>{copy.title}</span></nav><div className="article-media"><img src="/images/mistfall/loot.jpg" alt="Mistfall Hunter official artwork" /><span>{site.home.mediaLabel}</span></div><h1>{copy.title}</h1><p className="article-lede">{copy.lede}</p><div className="ad-slot" aria-hidden="true" />{useResearch ? <ResearchArticles articles={researchArticles} locale={locale} /> : <div className="article-copy">{copy.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{copy.bullets.length ? <ul>{copy.bullets.map((bullet) => <li key={bullet}>{bullet}</li>)}</ul> : null}{isCommunity ? <div className="official-links-list"><Link href={officialLinks.website}>{site.footer.website} ↗</Link><Link href={officialLinks.steam}>{site.footer.steam} ↗</Link><Link href={officialLinks.steamCommunity}>{site.footer.community} ↗</Link><Link href={officialLinks.discord}>{site.footer.discord} ↗</Link><Link href={officialLinks.youtube}>{site.footer.youtube} ↗</Link><Link href={officialLinks.x}>X ↗</Link></div> : null}</div>}</article></SiteFrame>;
}
