import Link from "next/link";
import { localizedPath, officialLinks, type Locale, siteCopy } from "../lib/site-data";
import { SiteFrame } from "./site-frame";

export type SectionKey = "beginner-guide" | "extraction" | "bosses" | "codes" | "tier-list" | "updates" | "community" | "maps-and-loot";

type SectionContent = { title: string; lede: string; paragraphs: string[]; bullets: string[] };

const sectionCopy: Record<Locale, Record<SectionKey, SectionContent>> = {
  en: {
    "beginner-guide": { title: "Beginner Guide", lede: "Start with the controls, first loadout, extraction loop, and safe early routes described in the research brief.", paragraphs: ["Mistfall Hunter is a high-stakes PvPvE extraction ARPG. Learn the basic controls and extraction loop before risking valuable gear. Specific control bindings and item recommendations are 待确认."], bullets: ["Understand the extraction loop before risking valuable gear.", "Use the official channels for current control and system changes.", "Class-specific recommendations are 待确认."] },
    extraction: { title: "How Extraction Works", lede: "The research brief describes solo and trio runs, map objectives, Returner Woodlings, and the need to leave with your haul.", paragraphs: ["A successful run means making progress and extracting your loot before the mist takes everything. Exact map objectives, extraction timings, and route details are 待确认."], bullets: ["Solo and three-player squad play are listed in the research brief.", "Returner Woodlings are named as an extraction element.", "Detailed extraction rules are 待确认."] },
    bosses: { title: "Bosses & Mist Lords", lede: "Mist Lords are mentioned in the official research brief; boss names, drops, phases, and tactics are not yet verified here.", paragraphs: ["This page intentionally avoids invented boss tables. We will add a boss guide only when a name, drop, or mechanic can be traced to an official source."], bullets: ["Mist Lords: mentioned in the research brief.", "Boss names and confirmed drops: 待确认.", "Boss tactics and phase data: 待确认."] },
    codes: { title: "Codes Snapshot", lede: "暂无官方可验证兑换码。", paragraphs: ["No redeemable code string was provided by the current official research snapshot. The latest Steam notice describes Moonlight Nectar x5, Pro Combat Bag x2, and Advanced Combat Bag x2 delivered through in-game mail, not through a redemption field. This page keeps the code status explicit instead of publishing guesses."], bullets: ["Current verified code: 暂无.", "Official reward channel found: in-game mail.", "Code system or future code: 待确认."] },
    "tier-list": { title: "Tier List", lede: "A verified class ranking is not available in the current research materials.", paragraphs: ["Because class names, skills, and balance values are not confirmed in the source brief, this wiki does not fabricate a tier list."], bullets: ["Playable classes listed: 6.", "Class-by-class ranking: 待确认.", "Balance data: 待确认."] },
    updates: { title: "Official Updates", lede: "A source-labeled timeline for the official live updates and roadmap status.", paragraphs: ["The official Steam notices report an August 12, 2026 update with Soul Harvest, a Fate Chart stage, a World Chat blocklist function, Xbox real-time voice chat, balance changes, and bug fixes. An August 14 notice says server configuration adjustments reduced intermittent stuttering, while optimization remains ongoing."], bullets: ["Aug 12, 2026 — Soul Harvest and other live-update changes.", "Aug 14, 2026 — server-stutter optimization status; issues are still being investigated.", "Brandrgarde Solo — official roadmap target for the middle of Season 1, September; exact day 待确认."] },
    community: { title: "Official Community & Links", lede: "Use the official website, Steam pages, Discord directory, X account, and YouTube channel for primary updates.", paragraphs: ["This wiki links to official destinations only. Community tools, mirrors, and unverified guides are not treated as primary sources."], bullets: [] },
    "maps-and-loot": { title: "Maps, Bosses & Loot", lede: "The research brief names Gyldenmist, Mist Lords, relics, loot priorities, and harder expeditions as core reference topics.", paragraphs: ["The exact map names, loot tables, affixes, and boss drops are not fully present in the current source material. Those details remain 待确认 until verified."], bullets: ["Gyldenmist: named as the setting pressure.", "Relics and loot: named as extraction rewards.", "Detailed maps, affixes, and drops: 待确认."] },
  },
  ru: {
    "beginner-guide": { title: "Гайд новичка", lede: "Начните с управления, первого комплекта, цикла extraction и безопасных маршрутов.", paragraphs: ["Mistfall Hunter — PvPvE extraction ARPG с высокой ценой ошибки. Точные бинды и рекомендации по предметам ожидают подтверждения."], bullets: ["Изучите цикл extraction перед риском ценной экипировки.", "Следите за официальными каналами.", "Рекомендации по классам ожидают подтверждения."] },
    extraction: { title: "Как работает extraction", lede: "В брифе указаны одиночные и троечные рейды, цели карты и Returner Woodling.", paragraphs: ["Нужно вынести добычу до того, как туман заберёт всё. Точные правила и маршруты ожидают проверки."], bullets: ["Одиночная игра и отряд из трёх игроков.", "Returner Woodling назван элементом эвакуации.", "Подробные правила ожидают подтверждения."] },
    bosses: { title: "Боссы и Mist Lords", lede: "Mist Lords упомянуты в исследовательском брифе; имена, дроп и тактики пока не подтверждены.", paragraphs: ["Мы не добавляем выдуманные таблицы боссов и будем расширять раздел после проверки официального источника."], bullets: ["Mist Lords упомянуты в брифе.", "Имена и дроп ожидают подтверждения.", "Тактики и фазы ожидают подтверждения."] },
    codes: { title: "Снимок кодов", lede: "Официально подтверждённых кодов пока нет.", paragraphs: ["В текущем исследовательском снимке нет кода для активации. Здесь не будут публиковаться догадки."], bullets: ["Проверенный код:暂无.", "Награды:暂无.", "Статус источника: ждём официальный проверяемый код."] },
    "tier-list": { title: "Тир-лист", lede: "Проверенного рейтинга классов в текущих материалах нет.", paragraphs: ["Названия, навыки и баланс классов не подтверждены, поэтому мы не создаём выдуманный тир-лист."], bullets: ["Игровых классов: 6.", "Рейтинг классов: ожидает подтверждения.", "Данные баланса: ожидают подтверждения."] },
    updates: { title: "Официальные обновления", lede: "Таймлайн официального обновления и исследовательских снимков.", paragraphs: ["Бриф фиксирует обновление 12 августа 2026 года и более 1 миллиона присоединившихся игроков. Онлайн 13 августа — временный снимок."], bullets: ["12 авг. 2026 — снимок обновления; 1M+ игроков.", "13 авг. 2026 — 14 941 онлайн в исследовании.", "29 июл. 2026 — дата запуска в снимке."] },
    community: { title: "Официальное сообщество", lede: "Официальный сайт, страницы Steam, Discord, X и YouTube — основные источники.", paragraphs: ["Здесь собраны только официальные направления. Непроверенные руководства не считаются первичным источником."], bullets: [] },
    "maps-and-loot": { title: "Карты, боссы и добыча", lede: "В брифе названы Gyldenmist, Mist Lords, реликвии, добыча и сложные экспедиции.", paragraphs: ["Названия карт, таблицы добычи, аффиксы и дроп боссов в текущих материалах раскрыты не полностью и ожидают проверки."], bullets: ["Gyldenmist назван источником давления мира.", "Реликвии и добыча названы наградами extraction.", "Карты, аффиксы и дроп ожидают подтверждения."] },
  },
  de: {
    "beginner-guide": { title: "Einsteiger-Guide", lede: "Beginne mit Steuerung, erstem Loadout, Extraction-Loop und sicheren frühen Routen.", paragraphs: ["Mistfall Hunter ist ein PvPvE-Extraction-ARPG mit hohem Risiko. Genaue Tastenbelegung und Item-Empfehlungen sind zu bestätigen."], bullets: ["Lerne den Extraction-Loop vor wertvoller Ausrüstung.", "Nutze offizielle Kanäle für Änderungen.", "Klassenempfehlungen sind zu bestätigen."] },
    extraction: { title: "Wie Extraction funktioniert", lede: "Der Recherchebrief nennt Solo- und Dreierläufe, Kartenziele und Returner Woodling.", paragraphs: ["Die Beute muss vor dem Nebel extrahiert werden. Genaue Regeln und Routen sind zu bestätigen."], bullets: ["Solo und Dreierteam sind gelistet.", "Returner Woodling wird als Extraction-Element genannt.", "Detaillierte Regeln sind zu bestätigen."] },
    bosses: { title: "Bosse und Mist Lords", lede: "Mist Lords werden im Recherchebrief erwähnt; Namen, Drops und Taktiken sind noch nicht verifiziert.", paragraphs: ["Wir ergänzen keine erfundenen Boss-Tabellen und warten auf offizielle Nachweise."], bullets: ["Mist Lords werden genannt.", "Namen und Drops: zu bestätigen.", "Taktiken und Phasen: zu bestätigen."] },
    codes: { title: "Codes-Snapshot", lede: "暂无 offiziell bestätigte Codes.", paragraphs: ["Im aktuellen offiziellen Recherche-Snapshot wurde kein einlösbarer Code gefunden. Vermutungen werden nicht veröffentlicht."], bullets: ["Verifizierter Code:暂无.", "Belohnungen:暂无.", "Quellenstatus: offizieller Code noch ausstehend."] },
    "tier-list": { title: "Tier-Liste", lede: "Eine verifizierte Klassenrangliste liegt in den aktuellen Materialien nicht vor.", paragraphs: ["Da Namen, Skills und Balancewerte nicht bestätigt sind, erstellt dieses Wiki keine erfundene Tier-Liste."], bullets: ["Spielbare Klassen: 6.", "Klassenranking: zu bestätigen.", "Balancewerte: zu bestätigen."] },
    updates: { title: "Offizielle Updates", lede: "Eine quellenmarkierte Timeline zu Update und Recherche-Snapshots.", paragraphs: ["Der Brief nennt ein Update am 12. August 2026 und mehr als 1 Million beigetretene Spieler. Die Online-Zahl ist ein Snapshot vom 13. August."], bullets: ["12. Aug. 2026 — Update-Snapshot; 1M+ Spieler.", "13. Aug. 2026 — 14.941 online im Recherche-Snapshot.", "29. Juli 2026 — Startdatum im Snapshot."] },
    community: { title: "Offizielle Community", lede: "Offizielle Website, Steam, Discord, X und YouTube sind die primären Quellen.", paragraphs: ["Diese Seite verlinkt nur offizielle Ziele. Unverifizierte Guides gelten nicht als Primärquelle."], bullets: [] },
    "maps-and-loot": { title: "Karten, Bosse und Beute", lede: "Der Brief nennt Gyldenmist, Mist Lords, Relikte, Beuteprioritäten und Expeditionen.", paragraphs: ["Kartennamen, Beutetabellen, Affixe und Boss-Drops sind in den aktuellen Quellen nicht vollständig enthalten und zu bestätigen."], bullets: ["Gyldenmist wird als Weltdruck genannt.", "Relikte und Beute werden als Extraction-Ziele genannt.", "Karten, Affixe und Drops: zu bestätigen."] },
  },
  "pt-br": {
    "beginner-guide": { title: "Guia para iniciantes", lede: "Comece pelos controles, primeiro equipamento, ciclo de extração e rotas seguras.", paragraphs: ["Mistfall Hunter é um extraction ARPG PvPvE de alto risco. Bindings e recomendações de itens estão a confirmar."], bullets: ["Aprenda o ciclo de extração antes de arriscar equipamentos valiosos.", "Acompanhe os canais oficiais.", "Recomendações por classe estão a confirmar."] },
    extraction: { title: "Como funciona a extração", lede: "O material cita incursões solo ou em trio, objetivos do mapa e Returner Woodling.", paragraphs: ["Extraia o saque antes que a névoa leve tudo. Regras e rotas exatas estão a confirmar."], bullets: ["Jogo solo e grupo de três jogadores.", "Returner Woodling é citado como elemento de extração.", "Regras detalhadas estão a confirmar."] },
    bosses: { title: "Chefes e Mist Lords", lede: "Mist Lords aparecem no material da pesquisa; nomes, drops e táticas ainda não foram verificados.", paragraphs: ["Não incluímos tabelas inventadas de chefes e aguardaremos fontes oficiais."], bullets: ["Mist Lords são citados no material.", "Nomes e drops: a confirmar.", "Táticas e fases: a confirmar."] },
    codes: { title: "Snapshot de códigos", lede: "暂无 códigos oficialmente verificáveis.", paragraphs: ["Nenhum código resgatável foi fornecido pelo snapshot oficial atual. Não publicaremos palpites."], bullets: ["Código verificado:暂无.", "Recompensas:暂无.", "Status: aguardando código oficial verificável."] },
    "tier-list": { title: "Tier List", lede: "Não há ranking de classes verificado nos materiais atuais.", paragraphs: ["Como nomes, habilidades e balanceamento não estão confirmados, esta wiki não inventa uma tier list."], bullets: ["Classes jogáveis: 6.", "Ranking por classe: a confirmar.", "Dados de balanceamento: a confirmar."] },
    updates: { title: "Atualizações oficiais", lede: "Linha do tempo com o update oficial e os snapshots da pesquisa.", paragraphs: ["O material registra uma atualização de 12 de agosto de 2026 e mais de 1 milhão de jogadores. O número online é um snapshot de 13 de agosto."], bullets: ["12 ago. 2026 — snapshot do update; 1M+ jogadores.", "13 ago. 2026 — 14.941 online no snapshot.", "29 jul. 2026 — data de lançamento no snapshot."] },
    community: { title: "Comunidade oficial", lede: "Site oficial, páginas da Steam, Discord, X e YouTube são as fontes primárias.", paragraphs: ["Esta página usa apenas destinos oficiais. Guias não verificados não são tratados como fontes primárias."], bullets: [] },
    "maps-and-loot": { title: "Mapas, chefes e saque", lede: "O material cita Gyldenmist, Mist Lords, relíquias, saque e expedições difíceis.", paragraphs: ["Nomes de mapas, tabelas de saque, afixos e drops de chefes não estão completos nas fontes atuais e estão a confirmar."], bullets: ["Gyldenmist é citado como pressão do mundo.", "Relíquias e saque são citados como objetivos.", "Mapas, afixos e drops: a confirmar."] },
  },
  zh: {
    "beginner-guide": { title: "新手指南", lede: "从操作、第一套装备、撤离循环与安全的前期路线开始。", paragraphs: ["Mistfall Hunter 是一款高风险 PvPvE 撤离 ARPG。具体按键与物品推荐待确认。"], bullets: ["承担高价值装备风险前先了解撤离循环。", "版本变化以官方频道为准。", "逐职业建议待确认。"] },
    extraction: { title: "撤离如何运作", lede: "调研资料提到单人和三人小队、地图目标、Returner Woodling，以及带着战利品离开。", paragraphs: ["需要在迷雾夺走一切前完成撤离。具体地图目标、时间与路线待确认。"], bullets: ["资料列出单人和三人小队。", "Returner Woodling 被列为撤离要素。", "详细撤离规则待确认。"] },
    bosses: { title: "首领与 Mist Lords", lede: "调研资料提到 Mist Lords；首领名称、掉落、阶段与战术尚未核验。", paragraphs: ["本页不会编造首领表格。只有官方来源确认名称、掉落或机制后才会补充。"], bullets: ["资料提到 Mist Lords。", "首领名称与已确认掉落：待确认。", "首领战术与阶段数据：待确认。"] },
    codes: { title: "兑换码快照", lede: "暂无官方可验证兑换码。", paragraphs: ["当前官方调研快照没有提供可兑换的代码。Steam 官方公告提到 Moonlight Nectar×5、Pro Combat Bag×2 和 Advanced Combat Bag×2 会通过游戏内邮件发放，而不是输入兑换码；本页明确保持为空，不发布猜测。"], bullets: ["当前已验证兑换码：暂无。", "已找到的官方奖励渠道：游戏内邮件。", "兑换码系统或未来代码：待确认。"] },
    "tier-list": { title: "强度榜", lede: "当前调研资料没有可核验的职业排名。", paragraphs: ["由于职业名称、技能与平衡数值尚未确认，本 Wiki 不编造强度榜。"], bullets: ["资料列出的可玩职业：6 个。", "逐职业排名：待确认。", "平衡数据：待确认。"] },
    updates: { title: "官方更新", lede: "标注来源的官方实时更新与路线图状态。", paragraphs: ["Steam 官方公告记录了 2026 年 8 月 12 日更新：加入 Soul Harvest、命运图表新阶段、世界聊天屏蔽功能、Xbox 实时语音聊天，以及职业平衡和问题修复。8 月 14 日公告称已调整所有服务器配置以减少间歇性卡顿，但优化仍在继续。"], bullets: ["2026/08/12——Soul Harvest 与其他实时更新内容。", "2026/08/14——服务器卡顿优化状态；问题仍在排查。", "Brandrgarde Solo——官方路线图目标为 S1 中期、9 月；具体日期待确认。"] },
    community: { title: "官方社区与链接", lede: "通过官网、Steam 页面、Discord 目录、X 与 YouTube 获取一手更新。", paragraphs: ["本 Wiki 只链接官方目的地。第三方镜像和未核验攻略不作为一手来源。"], bullets: [] },
    "maps-and-loot": { title: "地图、首领与战利品", lede: "调研资料将 Gyldenmist、Mist Lords、遗物、战利品优先级与高难远征列为核心参考主题。", paragraphs: ["当前资料没有完整提供地图名称、战利品表、词缀与首领掉落；这些信息待确认。"], bullets: ["Gyldenmist 被列为世界压力来源。", "遗物与战利品被列为撤离目标。", "地图、词缀与掉落：待确认。"] },
  },
};

export function ReferenceSectionPage({ locale, section }: { locale: Locale; section: SectionKey }) {
  const copy = sectionCopy[locale][section];
  const site = siteCopy[locale];
  const isCommunity = section === "community";
  return <SiteFrame locale={locale} currentPath={`/${section}`}><article className="reference-article"><nav className="breadcrumbs"><Link href={localizedPath(locale, "/")}>{locale === "zh" ? "首页" : "Home"}</Link><span>›</span><span>{copy.title}</span></nav><div className="article-media"><img src="/images/mistfall/loot.jpg" alt="Mistfall Hunter official artwork" /><span>{site.home.mediaLabel}</span></div><h1>{copy.title}</h1><p className="article-lede">{copy.lede}</p><div className="ad-slot" aria-hidden="true" /><div className="article-copy">{copy.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{copy.bullets.length ? <ul>{copy.bullets.map((bullet) => <li key={bullet}>{bullet}</li>)}</ul> : null}{isCommunity ? <div className="official-links-list"><Link href={officialLinks.website}>{site.footer.website} ↗</Link><Link href={officialLinks.steam}>{site.footer.steam} ↗</Link><Link href={officialLinks.steamCommunity}>{site.footer.community} ↗</Link><Link href={officialLinks.discord}>{site.footer.discord} ↗</Link><Link href={officialLinks.youtube}>{site.footer.youtube} ↗</Link><Link href={officialLinks.x}>Official X ↗</Link></div> : null}</div></article></SiteFrame>;
}
